In [1]:
>>> import numpy as np
>>> from sklearn.linear_model import LinearRegression
>>> X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
>>> # y = 1 * x_0 + 2 * x_1 + 3
>>> y = np.dot(X, np.array([1, 2])) + 3

In [2]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [3]:
y

array([ 6,  8,  9, 11])

In [6]:
>>> reg = LinearRegression().fit(X, y)


In [7]:
>>> reg.score(X, y)


1.0

In [8]:
>>> reg.coef_


array([1., 2.])

In [ ]:
>>> reg.intercept_


In [9]:
>>> reg.predict(np.array([[3, 5]]))

array([16.])